# Travis (http://travis-ci.org/) is a continuous integration
# service for open source projects. This file configures
# Travis to install and run "tox" test runner, which is
# configured in tox.ini file.

sudo: false
language: python
install:
  - pip install tox virtualenv virtualenvwrapper
script:
  - tox
  - which python
  - mktmpenv -p python3.6
  - which python
  - python setup.py bdist_wheel --universal
  - deactivate
  - which python
  - pip install dist/pydocstyle-*.whl
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
    - python: 2.7
      env: TOXENV=docs
