---
name: Test PyPI publish

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pypi-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry env use "3.7"
          poetry install
          poetry config repositories.testpypi https://test.pypi.org/legacy/

      - name: Bump version number
        run: poetry version ${{ github.event.release.tag_name }}

      - name: Build package
        run: poetry build

      - name: Publish package
        run: poetry publish -r testpypi -u __token__ -p ${{ secrets.TEST_PYPI_PASSWORD }}
